# Generated by Django 4.1.4 on 2023-04-12 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_apidata_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='apiname',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='url',
        ),
        migrations.AddField(
            model_name='apidata',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='apidata',
            name='value',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
