# Generated by Django 4.1.4 on 2023-04-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_apidata_apiname_remove_apidata_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='value',
            field=models.FloatField(max_length=20, unique=True),
        ),
    ]
