# Generated by Django 4.2 on 2023-04-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_mail', models.EmailField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='money',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
