# Generated by Django 4.2 on 2023-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_accountactivity_alter_money_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='splitbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='accountactivity',
            name='datafield',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='accountactivity',
            name='timefield',
            field=models.TimeField(null=True),
        ),
    ]
